using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using System.Net;
using System.Net.Mail;

namespace Aguai_Leave_Management_System
{
    public partial class EmployeeLeaves : System.Web.UI.Page
    {
        Database ds = new Database();
        SqlDataReader rd;
        string toAddress = null;
        string toUsername = null;

        protected void Page_Load(object sender, EventArgs e)
        {
            //btnReject.Attributes.Add("onClick", "return true;");
            if (!IsPostBack)
            {

                string query = "SELECT  L.ID,E.Emp_Reg_No,E.UserName,L.From_date,L.To_date,L.Description, LeaveType.Description as Type,T.Approver, 'Approval_Status'= CASE L.Approval_Status  WHEN '0' THEN 'Pending' WHEN '1' THEN 'Approved' WHEN '2' THEN 'Rejected' END  FROM LeaveManagement as L  left JOIN LeaveType ON LeaveType.ID=L.Type Left join EmployeeTable as E on E.ID = L.EmpID left join (select ID,UserName as Approver from EmployeeTable where ID=" + Session["EmpID"] + " and IsAdmin=1) as T on T.ID = L.Approver_ID where L.Approval_Status=0 and L.Approver_ID = " + Session["EmpID"] + " and E.IsActive=1 order by 1 DESC";
                ds.RunQuery(out rd, query);
                DataTable table = new DataTable();
                table.Load(rd);
                GridView1.DataSource = table;
                GridView1.DataBind();
                GridView1.Visible = true;
                rd.Close();
                ds.Close();
            }
        }

        protected void btnSearch_Click(object sender, EventArgs e)
        {
            string query = "SELECT  L.ID,L.From_date,L.To_date,L.Description,LeaveType.Description as Type,T.Approver, 'Approval_Status'= CASE L.Approval_Status  WHEN '0' THEN 'Pending' WHEN '1' THEN 'Approved' WHEN '2' THEN 'Rejected' END,L.Reason FROM LeaveManagement as L left JOIN LeaveType ON LeaveType.ID=L.Type Left join EmployeeTable as E on E.ID = L.EmpID  left join (select ID,UserName as Approver from EmployeeTable where IsAdmin = 1) as T on T.ID = L.Approver_ID where UserName like '%" + txtEmployee.Text + "%' order by 1 DESC";
            ds.RunQuery(out rd, query);
            DataTable table1 = new DataTable();
            table1.Load(rd);
            GridView3.DataSource = table1;
            GridView3.DataBind();
            GridView3.Visible = true;
            rd.Close();
            ds.Close();
        }

        protected void btnClear_Click(object sender, EventArgs e)
        {
            GridView3.Visible = false;
        }

        protected void GridView1_RowCommand(object sender, GridViewCommandEventArgs e)
        {
            //Show Individual Leave Application with Id

            if (e.CommandName == "Approve")
            {
                int id = Convert.ToInt32(e.CommandArgument);
                string query = "update[dbo].[LeaveManagement]  set Approval_Status=1 where ID=" + id + "";
                ds.RunCommand(query);
                ds.Close();

                string query1 = "SELECT L.ID as LID,E.ID as Emp,E.UserName,E.Email FROM LeaveManagement as L  Left join EmployeeTable as E on E.ID = L.EmpID  left join (select ID,UserName as Approver from EmployeeTable where IsAdmin = 1) as T on T.ID = L.Approver_ID where L.ID =" + id + "";

                ds.RunQuery(out rd, query1);

                while (rd.Read())
                {
                    toAddress = rd["Email"].ToString();
                    toUsername = rd["UserName"].ToString();
                }
                rd.Close();
                ds.Close();

                MailMessage message = new MailMessage();
                message.From = new MailAddress("veerudon456@gmail.com");

                message.To.Add(new MailAddress(toAddress));

                message.Subject = "Leave Notification.";

                message.Body = "Hi" + " " + toUsername + "," + "<br/> <br/>" + "Your Leave was" + " " + "Approved" + "<br/> <br/>" + "<br/> <br/>" + "******This is an Autogenerated Email, Please do not Reply.******";

                message.IsBodyHtml = true;

                // finaly send the email:
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";

                smtp.Port = 587;
                smtp.Credentials = new System.Net.NetworkCredential("veerudon456@gmail.com", "veerudon");

                smtp.EnableSsl = true;
                smtp.Send(message);

                Response.Redirect("~/Employee Leaves/EmployeeLeaves.aspx");
            }

            if (e.CommandName == "Reject")
            {
                Session["id"] = Convert.ToInt32(e.CommandArgument);
            }
        }

        protected void GridView3_RowCommand(object sender, GridViewCommandEventArgs e)
        {
            int id = Convert.ToInt32(e.CommandArgument);

            if (e.CommandName == "Cancel")
            {
                string query = "delete[dbo].[LeaveManagement] where Approval_Status=1 and ID=" + id + "";
                ds.RunCommand(query);
                ds.Close();
            }

            Response.Redirect("~/Employee Leaves/EmployeeLeaves.aspx");
        }

        protected void btnReject_Click(object sender, EventArgs e)
        {
            string query = "update[dbo].[LeaveManagement]  set Approval_Status=2 where ID=" + Session["id"] + "";
            ds.RunCommand(query);
            ds.Close();

            string query1 = "SELECT L.ID as LID,E.ID as Emp,E.UserName,E.Email FROM LeaveManagement as L  Left join EmployeeTable as E on E.ID = L.EmpID  left join (select ID,UserName as Approver from EmployeeTable where IsAdmin = 1) as T on T.ID = L.Approver_ID where L.ID =" + Session["id"] + "";

            ds.RunQuery(out rd, query1);

            while (rd.Read())
            {
                toAddress = rd["Email"].ToString();
                toUsername = rd["UserName"].ToString();
            }
            rd.Close();
            ds.Close();

            MailMessage message = new MailMessage();
            message.From = new MailAddress("veerudon456@gmail.com");

            message.To.Add(new MailAddress(toAddress));

            message.Subject = "Leave Notification.";

            message.Body = "Hi" + " " + toUsername + "," + "<br/> <br/>" + "Your Leave was" + " " + "Rejected" + "<br/> <br/>" + "<br/> <br/>" + "******This is an Autogenerated Email, Please do not Reply.******";

            message.IsBodyHtml = true;

            // finaly send the email:
            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";

            smtp.Port = 587;
            smtp.Credentials = new System.Net.NetworkCredential("veerudon456@gmail.com", "veerudon");

            smtp.EnableSsl = true;
            smtp.Send(message);

            Response.Redirect("~/Employee Leaves/EmployeeLeaves.aspx");
        }
    }
}