using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using System.Net;
using System.Net.Mail;

namespace Aguai_Leave_Management_System
{
    public partial class ApplyLeave : System.Web.UI.Page
    {
        Database ds = new Database();
        SqlDataReader rd;
        List<DateTime> holidays = new List<DateTime>();
        string toAdminAddress = null;

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                if (Session["username"] != null)
                {
                    lblregno.Text += Session["Emp_Reg_No"].ToString();
                }

                //populate  Type dropdown
                string query = "select * from LeaveType";
                ds.RunQuery(out rd, query);
                while (rd.Read())
                {
                    ddltype.Items.Add(new ListItem(rd["Description"].ToString(), rd["ID"].ToString()));
                }
                rd.Close();
                ds.Close();

                //populate  Approver dropdown
                string query1 = "select * from EmployeeTable where IsAdmin=1";
                ds.RunQuery(out rd, query1);
                while (rd.Read())
                {
                    //toAdminAddress = rd1["Email"].ToString();
                    ddlapprover.Items.Add(new ListItem(rd["FirstName"].ToString() + " " + rd["LastName"].ToString(), rd["ID"].ToString()));
                }
                rd.Close();
                ds.Close();
            }
        }

        protected void btnSubmit_Click(object sender, EventArgs e)
        {

            double leave = 0, diff, h = 0, w = 0;
            DataTable weeklyoffdays = (DataTable)Session["weekly_off"];
            DataTable holidaylist = (DataTable)Session["holiday"];
            DateTime Fromdate = DateTime.Today, Todate = DateTime.Today;
            Fromdate = DateTime.Parse(txtstartdate.Text);
            Todate = DateTime.Parse(txtenddate.Text);

            diff = Todate.ToOADate() - Fromdate.ToOADate() + 1;
            while (0 != Fromdate.CompareTo(Todate))
            {
                foreach (DataRow row in weeklyoffdays.Rows)
                {
                    foreach (var weeklyoff in row.ItemArray)
                    {
                        if (weeklyoff.Equals(Convert.ToString(Fromdate.DayOfWeek)))
                            w++;
                    }
                }

                foreach (DataRow row in holidaylist.Rows)
                {
                    foreach (var item in row.ItemArray)
                    {
                        var get = (DateTime)item;
                        if (0 == get.CompareTo(Fromdate))
                            h++;
                    }
                }
                Fromdate = Fromdate.AddDays(1);
            }
            leave = diff - (w + h);


            string query3 = "insert into LeaveManagement (EmpID,From_date,To_date,Description,Type,Approver_ID,leave) values (" + Convert.ToInt32(Session["EmpID"]) + ",'" + txtstartdate.Text + "','" + txtenddate.Text + "','" + txtdescription.InnerText + "'," + Convert.ToInt32(ddltype.SelectedValue) + "," + Convert.ToInt32(ddlapprover.SelectedValue) + "," + leave + ")";
            ds.RunCommand(query3);
            ds.Close();

            string query2 = "select Email from EmployeeTable where ID=" + ddlapprover.SelectedValue + "";
            ds.RunQuery(out rd, query2);
            while (rd.Read())
            {
                toAdminAddress = rd["Email"].ToString();
            }
            rd.Close();
            ds.Close();

            MailMessage message = new MailMessage();
            message.From = new MailAddress("veerudon456@gmail.com");

            message.To.Add(new MailAddress(toAdminAddress));
            message.Subject = "Leave Notification.";

            message.Body = "Hi" + " " + ddlapprover.SelectedItem + "," + "<br/> <br/>" + Session["username"].ToString() + " " + "Applied leave and the Details as below" + "<br/> <br/>" + "Type" + " " + ddltype.SelectedItem + " <br/> <br/> " + "From" + " " + txtstartdate.Text + "<br/> <br/>" + "To" + " " + txtenddate.Text + " " + "<br/> <br/>" + "Description" + " " + ":" + " " + txtdescription.InnerText + "<br/> <br/>" + "<br/> <br/>" + "******This is an Autogenerated Email.******";

            message.IsBodyHtml = true;

            // finaly send the email:
            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";

            smtp.Port = 587;
            smtp.Credentials = new System.Net.NetworkCredential("veerudon456@gmail.com", "veerudon");

            smtp.EnableSsl = true;
            smtp.Send(message);

            //insert apply leave data into database
           
            Response.Redirect("AppliedLeaves.aspx");
        }

        protected void btnClear_Click(object sender, EventArgs e)
        {
            //cleare the apply leave data while applying for leave
            ddltype.SelectedValue = null;
            txtdescription.InnerText = null;
            txtstartdate.Text = null;
            txtenddate.Text = null;
            ddlapprover.SelectedValue = null;
        }
    }
}